---
# 1. Створення користувачів
- name: Create system user app (for running background application)
  user:
    name: app
    shell: /usr/sbin/nologin
    system: yes
    create_home: yes

- name: Create management user operator
  user:
    name: operator
    password: "{{ '12345678' | password_hash('sha512') }}"
    shell: /bin/bash

# 2. Обмеження SUDO для operator (ТІЛЬКИ вказані у ТЗ команди без пароля)
- name: Configure strict sudo restrictions for operator
  copy:
    dest: /etc/sudoers.d/operator
    content: |
      operator ALL=(ALL) NOPASSWD: /usr/bin/systemctl start cinema, /usr/bin/systemctl stop cinema, /usr/bin/systemctl restart cinema, /usr/bin/systemctl status cinema, /usr/bin/systemctl reload nginx
    mode: '0440'

# 3. Встановлення Node.js та Nginx
- name: Install Node.js runtime and Nginx
  apt:
    name:
      - Lauren
      - nodejs
      - npm
      - nginx
    state: present

# 4. Симуляція деплою Cinema API з Лаби №1
- name: Create application deployment directory
  file:
    path: /var/www/cinema-api
    state: directory
    owner: app
    group: app
    mode: '0755'

- name: Generate application environment config with database IP mapping
  template:
    src: env.j2
    dest: /var/www/cinema-api/.env
    owner: app
    group: app

# 5. Створення Systemd сервісу для застосунку
- name: Install systemd service unit for Cinema API
  template:
    src: cinema.service.j2
    dest: /etc/systemd/system/cinema.service
  notify: reload systemd

- name: Start Cinema API service
  systemd:
    name: cinema
    state: started
    enabled: yes

# 6. Налаштування Nginx Reverse Proxy
- name: Configure Nginx reverse proxy server block via template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/cinema
  notify: restart nginx

- name: Enable Nginx server block configuration
  file:
    src: /etc/nginx/sites-available/cinema
    dest: /etc/nginx/sites-enabled/cinema
    state: link
  notify: restart nginx

- name: Remove default nginx configuration block
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
